name: Continuous Integration (PR Review)

on:
  pull_request
jobs:
  build-examples:
    runs-on: self-hosted
    if: contains( github.event.pull_request.labels.*.name, 'CI - Ready to run' )
    steps:
    - uses: actions/checkout@v2
    - name: Build all examples
      run: "echo '##debug##foo'"
  run-tests:
    runs-on: self-hosted
    if: contains( github.event.pull_request.labels.*.name, 'CI - Ready to run' )
    needs: build-examples
    steps:
    - uses: actions/checkout@v2
    - name: Run test cases on hardware
      run: "echo '##debug##bar'"
  remove-label:
    runs-on: self-hosted
    if: contains( github.event.pull_request.labels.*.name, 'CI - Ready to run' )
    steps:
    - uses: octokit/request-action@v2.0.0
      with:
        route: DELETE /repos/:repository/issues/:issue_number/labels/:name
        repository: ${{ github.repository }}
        issue_number: ${{ github.event.number }}
        name: 'CI - Ready to run'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Remove CI Label from PR
