name: Continuous Integration (PR Review)

on:
  pull_request:
    types: [labeled]
jobs:
  build-examples:
    runs-on: self-hosted
    if: contains( github.event.pull_request.labels.*.name, 'CI - Ready to run')
    steps:
    - uses: actions/checkout@v2
    - name: Build all examples
      run: ./extras/ci/scripts/build-examples.sh
  run-tests:
    runs-on: self-hosted
    if: contains( github.event.pull_request.labels.*.name, 'CI - Ready to run')
    needs: build-examples
    steps:
    - uses: actions/checkout@v2
    - name: Run test cases on hardware
      run: ./extras/ci/scripts/run-tests.sh
