name: CI

on:
  push:
    branches: master

jobs:
  build-examples:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - run: ./extras/ci/scripts/build-examples.sh
  run-tests:
    runs-on: self-hosted
    needs: build-examples
    steps:
    - uses: actions/checkout@v2
    - run: ./extras/ci/scripts/run-tests.sh